# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    # Step 1 - checkout main branch from GitHub
    - uses: actions/checkout@v3
    # Step 2 - Runs a single command using the runners shell
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'temurin'
        #server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        #settings-path: ${{ github.workspace }} # location for the settings.xml file
    # Step 3 - Have GitHub Actions build Maven project
    - name: Build with Maven
      run: |
        mvn clean compile assembly:single --file pom.xml
        mkdir staging && cp target/*.jar staging
      
      
      
    # Step 4 - Set up a cache for Maven
    - name: cache
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    # Step 5 - Persist workflow data as artifacts
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Foodimizer
        path: staging
